server:
  port: 8000
spring:
  application:
    name: hello-getway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:9090
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          #开启应用名称转发
          enabled: true
      routes:
      - id: hello-consumer-route
        uri: lb://hello-consumer
        predicates:
        - Path=/hello-consumer/**
feign:
  sentinel:
    enabled: true
logging:
  level:
    root: debug